---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ollama
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1m0s
  targetNamespace: ai

  values:
    ollama:
      gpu:
        enabled: false
        type: 'nvidia'

      models:
        pull:
          - mistral
          - llama2

        run:
          - mistral

    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    persistentVolume:
      enabled: true
      existingClaim: "pvc-ollama-data"

    ingress:
      enabled: true
      className: "internal-nginx"
      hosts:
        - host: ollama.rees.ca
          paths:
            - path: /
              pathType: Prefix
