---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ollama
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ollama

  values:
    ollama:
      gpu:
        enabled: true
        type: 'nvidia'

      models:
        - mistral
        - llama2

    ingress:
      enabled: true
      className: "internal-nginx"
      hosts:
        - host: ollama.rees.ca
          paths:
            - path: /
              pathType: Prefix
