apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: double-take
  namespace: flux-system
spec:
  chart:
    spec:
      chart: double-take
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 1m0s
  releaseName: double-take
  targetNamespace: default
  values:
    image:
      tag: 1.13.1 # {"$imagepolicy": "flux-system:double-take:tag"}
      pullPolicy: Always
    env:
      TZ: America/Toronto
    config:
      mqtt:
        host: mosquitto.default.svc.cluster.local:1883
      detect:
        match:
          confidence: 80
      frigate:
        url: http://frigate.default.svc.cluster.local:5000
        update_sub_labels: true
        attempts: {latest: 2, snapshot: 0, mqtt: true, delay: 0}
        cameras:
          - driveway
          - backyard
          - shed
          - sideyard
          - frontdoor
        image:
          height: 1440
      detectors:
        compreface:
          enabled: true
          url: http://compreface-ui.compreface.svc.cluster.local:8000/
          key: 363f4409-ed7a-44be-99a8-0cad2674459b
        deepstack:
          enabled: true
          url: http://deepstack.default.svc.cluster.local
    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: doubletake.rees.ca
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: double-take
                    port:
                      number: 3000
    persistence:
      data:
        enabled: true
        existingClaim: pvc-doubletake
