---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: double-take
  namespace: flux-system
spec:
  chart:
    spec:
      chart: double-take
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 1m0s
  releaseName: double-take
  targetNamespace: default
  values:
    image:
      tag: 1.12.0 # {"$imagepolicy": "flux-system:double-take:tag"}
      pullPolicy: Always

    env:
      TZ: America/Toronto
    config:
      mqtt:
        host: mqtt.rees.ca:1883
      detect:
        match:
          confidence: 80
      frigate:
        url: http://frigate.rees.ca:5000
        attempts: { latest: 2, snapshot: 0, mqtt: true, delay: 0 }
        cameras:
          - driveway
          - backyard
          - shed
          - sideyard
          - frontdoor
        image: 
          height: 1440
      detectors:
        compreface:
          enabled: true
          url: http://compreface.rees.ca:8000/
          key: 396383db-644f-47fa-b087-ddd209930dba
    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
        - host: doubletake.rees.ca
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: double-take
                port:
                  number: 3000
    persistence:
      data:
        enabled: true
        existingClaim: pvc-doubletake

