---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    tag: v1.2.1
  url: https://github.com/kubernetes-sigs/gateway-api
  ignore: |
    /*
    !/config/crd/standard
