---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts

