---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    installCRDs: true
    config:
      featureGates:
        ACMEHTTP01IngressPathTypeExact: false

    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    webhook:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: monitoring-kube-prometheus-stack
