---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  install:
    crds: Create
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace

  values:
    installCRDs: true
    config:
      featureGates:
        ACMEHTTP01IngressPathTypeExact: false

    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: monitoring-kube-prometheus-stack
