---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBWjrENEZ/2iz1tME5mvpp/cahHimDRSbnJR5fO9acSQblLKwqdqaP8ybVM5VqOM4iU7Qf9OaPEk0OcqHXAe9xDiQx8wi9DdfJ/Wuzlhw5Y957U1Cy1KmNdfJofPZ1FKmA5AGclm1sawbuj0rx8fHkjZzRAfUIK5yUShBnQfHTRcCoiAXex20GdhuHJERT9k3pLADplnJvfMnJqeVyvCY0dlvfzUC/QdL+Rzje2tdDV+3r3cqNfWqCThcJIynVBXeLUxFUXAbDy938FzuB6Box4zn/EIKLuf5uVHwNYgjUAIvHOxj5TsHRuXeSSzg+ye+n4c8mEFKOFpkarHRiyI1CAGYp+3ebgb+POWRilsb/dRFSJo1ELj1ZFNb2dKEvomBDO8198x9Gr4867AOigqRLpEpMen7Dsho5+ke5lUwkYPs6UMeNsvpG+aktNhOmkwCeOSgkSlhf68XCSp2K7jANuTHKwuhzf7xW+ZNqgju1qvVrt/oDnoxBs4QtFn2LIrlkRIJyaUowOnSh2MvUmsgpkr+18Z133Ho8amzgSsSHumHp3s/0ECWrPYnAUeX/8j8pRKHHv1SarGvG9lLNOT5ou6YSRRtqS43ghmPyoHeKDdu6YirA6q4B6MWxwiYy/scBzQflKkO0Bv4hKYU+NpjXaGzRD+DgETdAp8xYBx5rEeKfwFjs14PN/c8H1CNd66RbyHuQXxtTCJLU5p2vlg0Ns+tFqO9CzHwmxiUpBuYdJJgSclqhsNZdicUJi2K7AcU8dAIHEVw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
