---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-downloads
  namespace: default
spec:
  capacity:
    storage: 45Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/shared/downloads
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-downloads
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-media-downloads
  resources:
    requests:
      storage: 45Ti

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-videos
  namespace: default
spec:
  capacity:
    storage: 45Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/shared/videos
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-videos
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-media-videos
  resources:
    requests:
      storage: 45Ti

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-music
  namespace: default
spec:
  capacity:
    storage: 45Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/shared/music
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-music
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-media-music
  resources:
    requests:
      storage: 45Ti

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-photos
  namespace: default
spec:
  capacity:
    storage: 45Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/shared/photos
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-photos
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-media-photos
  resources:
    requests:
      storage: 45Ti

