---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: nfd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: node-feature-discovery
  targetNamespace: node-feature-discovery
  values:
    worker:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      config:
        sources:
          pci:
            deviceClassWhitelist:
              - "0200"
              - "03"
              - "12"
              - "08"
              - "0300"
              - "0403"
          usb:
            deviceClassWhitelist:
              - "0e"
              - "ef"
              - "fe"
              - "ff"
              - "02"
              - "e0"
