---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wyzebridge
  namespace: media
spec:
  encryptedData:
    WYZE_EMAIL: AgAjmurQiiyaVr+Tkr8ZJv1JCgKnq1ulr9THw4eiOF099JlLUjSmXdeTCXmMiUSHtP3Ab+TTz+kjariYWnwukjijkbPyeUNVn/tCKoll2DiE4grsPMVjol3c9gTmWrcbSfZN19GTe8+qPnvyawsqJsDRi75nT+hb+KGgPve9JUkXjsMo32oUmF2f/+aaG0bu0TXOVTX6nYbmSLMbWVoPgAGOAfL40ihb6y7kp8WqoEytur6HdBwBbSm/Kz12Zd849g9QQKxkhUvgEXQTUP4qIYO1Oh92+x4yjZm/0ihlVC2tjJnFuRTvaK0CJX3VF6l6eaOUx3Mrhwh+y/klKbemwi6WZMoOlujVWxb3bkq9b4SoyVtx/P/CB7Drj6Ju7bhcoZJt7Z7NKfJtNFOaN4khma1AYdfT0/0zvzPk/Sa0qqOZ6O6tsLPvIJduh+GLGwue8NDNOfJiL8Vta65yrydeBpn+HyXkm8N+V3UtKFj50GAIW8Cx5/Pj1AYByh9JgtTB0907vLFUQ8/jLCBRZMR1EkzjafY2KtZBKMEYJz64gicOHkt4G+WFqToJNFgN5P4rJxuWC/diBxWYFPUAubW9L9eIeHsvRjX1hcx7uiRtHqciajzL3cjqPspNpT6Wwljyj0+tABk9+amHexU1EXSrWMXZp5E4eZKEwh4Ub8mWcamywaAdrBVw5jQkIPZQjc52DP/NA6NYL9sVD0/55aswvw==
    WYZE_PASSWORD: AgCEdwlWXH2HLYuIj2Z+zv09T4Bw4BLe4DhsA8aDcaGJ0lAiDKRXYA3OHV8g3WCsJxTIVtVeDT1x2RqoS4Ad+L6nMTBsf9Zu4DqpY17u40jYWJP3GQpmvtDlzuCfJgjEkV8SiuOOSIfENmqumsckbYNd9pdUXrT9PkCprnfvwygWMh6GDD9GpTCPOwwJgEGf63Jvf2exkMssFhzF6UeanvFGYHMexOIxUqkLCmKnvKzJVMp8UrIW46KekDkj8Bv0n//aLS40Vg6kJ6rcnm6T2mTMCzYUt8OWmH77Eo9HwiYlIIcBQtCF11PMR20jhEJNgKgLwRj3yjDy+rWNTzTwYkgLdRIbOWRT1jzgZ7GmJiHC8cgB26gOEl9GabMpxkNb7FGC0qwonUJDgeRPz5qVyF4/g0PVqOEH0PB+CMJf7jkVlHtU26Zrj7+JJjxZQKpLt+arVF4jMFBbkQfzyOAOrL7+ll3XXwpJ2VxS83meAjun1yeiWp1ivbtfm1ySnfdBj9X9OPPjlbMKDkNXVgqtr350h8Wg6Usb6ATODAjSeyo+aqPJcNFnOvDj4CZwrLAthH/jNn50Po/N71QmFk1Fy7bfM1HYC/zM6DUNToKHOh07HIEcLX8ymli/xSZWxFxRhuIjJfyElDYe4rs+HawIRjh8k9/72H67pclk3bjdeYG2kx8muzZ6npKnkoQYYTGpUvex7FTD+TxSKh9VjWzAy4bV
  template:
    metadata:
      name: wyzebridge
      namespace: media
    type: Opaque
