apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wyzebridge
  namespace: default
spec:
  encryptedData:
    WYZE_EMAIL: AgBcsOIQdNS5DpvoJ0SRTNo3fV11uXUKYn430Idi8Lz1LbQq7Hl6PIWTpSmMNsXFX48Uz6ABbRw3mkv+s21Z9Q0nENSZIjv15/c7mMWOE8rGb63EujtrGn6FqXNlPNNxyWbeoSCczGVqZr0XhTex2onW8KZui3rkwMCvbUuFhQoR8Ufc7QJMdL6AxvTQmSq8Uf0oO0kTcuu1XsCh4zZ8oRkNvZrJhobM4TfEt+R0ytc81lrWkTfCgji4/2GeJeZMw4odUvIqBIJkknNJJDL5RG1dV3sVYLrex+iUvP9xjmU6bS1WD1MiEki/wuuloG/Nskz6LCDA70RNQfMf7XpJwbAaKi1tbweGdIZwBx0w+6UWlqQYMmXyDPXJA2nKeBb1iIY0IIoPHTccxQzXA/FUIZI9mn67FHhImiHrK1ot7OTo1zqHnryUtlC4jtwlinq0IoR8lw/GS87XPh6/yqkcZAtGCvrnmFeaIvvw3zckEKz9bkU4+Yf/EGOtaLi5g4J9Em0exfLjqFqiSWzNByuuh+cxSAyy0hS9KqEeSkY8XGr+Ib4PGoSqXz+8LNeK0bE4Yi6+yjfyZ0jLVor5hW2e6ULssnUDcjE/C92hvxrVljQncdU4AuHDfJvssK6tnDtfeo2EASRMN7EJylYLnUeHyICWfQBDYKOrWdkg7iviSlu3MSx/RGDBHrzIQkeGK5ACmqoRoG+BwpjY9/j5+aSs7w==
    WYZE_PASSWORD: AgBjYKirNaPhY5Ca+3dniJx3rmywlvTzlAu1PmUVNxSlpKugGVCNwyjBgCyWZVgedKWqPrdsRTisuLOmTki9tlBohvjQTxWKEnPb6e/KffZAjZXAXiolo7Ole3/cyLJgpstX78fqNVTr8tFAA8myBE15dOJEchf9g9e+Ax7RpPMWLcJiM5P20tH6FFKRCGINZ1xa7JKwIY7XINfiNunKedcFQxfs0hOSHZDCDhHD4vOLVlrV5P8vG6XnVUSaAuVFJdh7GQ72VRS104b4j1/m2kjG50hSJr6nyVWJ58BnsBtBd8Hb3reyvAIzuJJ5j9dGnDfODQYFk8ODaCrEd9N31QeS/FAetZWaI41oIOp9RUA+w7M3Q8YFqJMVjWymDWsLRXoKT9JTZdx9cVwxgvqtSIIT3yrcsSA6kWg+LAbYfNOhhtN+2L+fX5kLwGqiC2UZ6FzdY9IPV62x2kKmILtN+uNB4sOeYni1WXF+jNKNdceo88ASQlg82XbZ03IoRl/Qtc1D661OJ2AqQ8D7vpIqg4plDSbe37UEDYiiyogvOojHp+1Dqx9b2fGbybKgsQUbJS7ShchrJLCjUg81xTbAVGFshu/RMI67uEKRrbDRAtAji8EJL9eowe5ODH8YG+s7lrClSUKPxWVpTa+Ix8BJhYkFxq2h8Qw8ZNARmjZY6RRQjp9SYZZsfskbN76wfbo1OpogyE6qrt7dz0IIeZnUAygs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wyzebridge
      namespace: default

