---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Create
  interval: 30m0s
  releaseName: metallb
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    configInline:
      address-pools:
      - addresses:
        - 10.0.0.185-10.0.0.190
        - 10.0.0.50/32
        - 10.0.0.30/32
        - 10.0.0.34/32
        - 10.0.0.35/32

        name: default
        protocol: layer2

