---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Create
  interval: 30m0s
  releaseName: metallb
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
