---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1m0s
  targetNamespace: metallb-system

  values:
    controller:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
    speaker:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
    prometheus:
      serviceAccount: prometheus-metallb
      rbacPrometheus: true
      namespace: monitoring
      podMonitor:
        enabled: false
        additionalLabels:
          release: monitoring-kube-prometheus-stack
      serviceMonitor:
        enabled: true
        speaker:
          additionalLabels:
            release: monitoring-kube-prometheus-stack
        controller:
          additionalLabels:
            release: monitoring-kube-prometheus-stack

      prometheusRule:
        enabled: true
        additionalLabels:
          release: monitoring-kube-prometheus-stack

