apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  generation: 2
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: myipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.240-10.0.0.250
  - 10.0.0.50/32
  - 10.0.0.30/32
  - 10.0.0.34/32
  - 10.0.0.35/32
  autoAssign: true
  avoidBuggyIPs: false

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
