---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1m0s
  targetNamespace: metallb-system

  values:
    prometheus:
      serviceAccount: prometheus-metallb
      rbacPrometheus: true
      namespace: monitoring
      podMonitor:
        enabled: false
        additionalLabels:
          release: monitoring-kube-prometheus-stack
      serviceMonitor:
        enabled: true
        speaker:
          additionalLabels:
            release: monitoring-kube-prometheus-stack
        controller:
          additionalLabels:
            release: monitoring-kube-prometheus-stack

      prometheusRule:
        enabled: true
        additionalLabels:
          release: monitoring-kube-prometheus-stack

