apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwakeword
  namespace: default
spec:
  selector:
    matchLabels:
      app: openwakeword
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
      - env:
        - name: TZ
          value: America\Toronto
        imagePullPolicy: IfNotPresent
        name: openwakeword-k8s
        image: rhasspy/wyoming-openwakeword:latest
        #args:
        #- --preload-model 'ok_nabu'
        ports:
        - containerPort: 10400
          protocol: TCP

      hostname: openwakeword
---
apiVersion: v1
kind: Service
metadata:
  name: openwakeword
  namespace: default
  labels:
    app: openwakeword
  annotations:
    metallb.universe.tf/allow-shared-ip: wyoming-svc
    metallb.universe.tf/ip-allocated-from-pool: myipaddresspool
spec:
  ports:
  - name: openwakeword-10400
    port: 10400
    protocol: TCP
    targetPort: 10400
  selector:
    app: openwakeword
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.0.0.247
