apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: media
spec:
  selector:
    matchLabels:
      app: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisper
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: TZ
          value: America\Toronto
        imagePullPolicy: IfNotPresent
        name: whisper-k8s
        securityContext:
          allowPrivilegeEscalation: false
        image: rhasspy/wyoming-whisper:3.2.0 # {"$imagepolicy": "flux-system:whisper"}
        args:
        - --model=base
        - --language=en
        ports:
        - containerPort: 10300
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: 10300
          failureThreshold: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 10300
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 10300
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /data
          name: whisper-data
      hostname: whisper
      volumes:
      - name: whisper-data
        persistentVolumeClaim:
          claimName: pvc-whisper-data
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: media
  labels:
    app: whisper
  annotations:
    lbipam.cilium.io/sharing-key: wyoming-svc
spec:
  ports:
  - name: whisper-10300
    port: 10300
    protocol: TCP
    targetPort: 10300
  selector:
    app: whisper
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.0.0.247
