apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: default
spec:
  selector:
    matchLabels:
      app: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - env:
        - name: TZ
          value: America\Toronto
        imagePullPolicy: IfNotPresent
        name: whisper-k8s
        image: rhasspy/wyoming-whisper:latest
        args:
        - --model=base
        - --language=en
        ports:
        - containerPort: 10300
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /data
          name: whisper-data
      hostname: whisper
      volumes:
      - name: whisper-data
        persistentVolumeClaim:
          claimName: pvc-whisper-data
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: default
  labels:
    app: whisper
  annotations:
    metallb.universe.tf/allow-shared-ip: wyoming-svc
    metallb.universe.tf/ip-allocated-from-pool: myipaddresspool
spec:
  ports:
  - name: whisper-10300
    port: 10300
    protocol: TCP
    targetPort: 10300
  selector:
    app: whisper
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.0.0.247
