apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: default
spec:
  encryptedData:
    password: AgAHNJ4ZI/6JFGMEoyd6LE9EFZ11mGTH6D6+2dwIrKXF8IgWHu6bxDHBS9YcX8pMHmeuOzD2q2LvArLklXxXUvFiJKx0oUq3+QeIllX7Z6Zk5Q/hKuQfxQ9duUA3fVam+fwDgMtaJ5hwQSe1FL+J5eg87bHA3ZIhm8sRzU2pgCs0Kb0f2cPJQ0NhPZyBfzYAu3CWuxkaEHeyFNxrJundVIAixVnNdzE3r7w5PIk6Fi3o/LSORaz++F9R8llx3iYyc6AfmDQmUTeQtpLPgvcbkO0FhD+obbbbUkYnhTH2hcNRjftZ2nmYhM81NMP5DQtKWTZ1poHgW5O0Fo9h0rdr+a2pMUvpZOjiSUxSeIHh3xAMMR2V9xR6LJac6nYydZffPp7fU6SapPsMB9LaJhzsUgOghNjIAvirsT0IBiLaZ0LYN5m/GWgDTLm7RCLE/1o9FBGiumsAagcWjqUaovsw/OM5Ov5Jglq8rnSy27Aa93o3DZfNy8g39ErpotSxpwQOIQ/o9KioCD37EJ3hbw1/ng7KTBjmv/lxQ9Fteli5rCrMhG1Rp9ghrjAmjp2ZeV6mxaQcWWU07KWTrJsuTgKAYOh6DEAH9xNMhIFArsAJH6i56dbGLP6k8UgqyT6xzTj1jaLjXbBYVEt6MD4jJRsNb9W+Y9uIg2TD/wuDH77ZkH6P86Lr/eO2ppzA6mfdV4oGaj7PvirSHbC66Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: default

