apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  interval: 60m0s
  targetNamespace: default
  values:
    image:
      tag: 2022.09.3 # {"$imagepolicy": "flux-system:pihole:tag"}
    replicaCount: 3
    extraEnvVars: {"FTLCONF_REPLY_ADDR4": "10.0.0.35"}
    persistentVolumeClaim:
      enabled: true
      existingClaim: "pvc-pihole-config"
      accessModes:
      - ReadWriteMany
    serviceWeb:
      loadBalancerIP: 10.0.0.35
      annotations:
        metallb.universe.tf/allow-shared-ip: mc-pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 10.0.0.35
      annotations:
        metallb.universe.tf/allow-shared-ip: mc-pihole-svc
      type: LoadBalancer
