---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-nginx
  namespace: flux-system
spec:
  targetNamespace: internal-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    crds: Create
  interval: 10m0s
  releaseName: internal-nginx
  upgrade:
    crds: CreateReplace
  values:
    controller:
      electionID: internal-ingress-controller-leader
      replicaCount: 2
      autoscaling:
        enabled: true
 
      ingressClass: internal-nginx
      ingressClassResource:
        name: internal-nginx  # default: nginx
        enabled: true
        default: false
        ingressClassByName: true
        controllerValue: "k8s.io/internal-nginx"

      service:
        loadBalancerIP: "10.0.0.50"
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
        prometheusRule:
          enabled: true
          namespace: monitoring
          rules: 
            - alert: NGINXConfigFailed
              expr: count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
              for: 1s
              labels:
                severity: critical
              annotations:
                description: bad ingress config - nginx config test failed
                summary: uninstall the latest ingress changes to allow config reloads to resume
            - alert: NGINXCertificateExpiry
              expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()) < 604800
              for: 1s
              labels:
                severity: critical
              annotations:
                description: ssl certificate(s) will expire in less then a week
                summary: renew expiring certificates to avoid downtime
            - alert: NGINXTooMany500s
              expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
              for: 1m
              labels:
                severity: warning
              annotations:
                description: Too many 5XXs
                summary: More than 5% of all requests returned 5XX, this requires your attention
            - alert: NGINXTooMany400s
              expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
              for: 1m
              labels:
                severity: warning
              annotations:
                description: Too many 4XXs
                summary: More than 5% of all requests returned 4XX, this requires your attention
    spec.controller: k8s.io/internal-nginx
