---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-nginx
  namespace: flux-system
spec:
  targetNamespace: internal-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: internal-nginx
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controller:
      electionID: internal-ingress-controller-leader
      replicaCount: 3
      minAvailable: 2
      ingressClass: internal-nginx
      ingressClassResource:
        name: internal-nginx  # default: nginx
        enabled: true
        default: false
        ingressClassByName: true
        controllerValue: "k8s.io/internal-nginx"

      service:
        loadBalancerIP: "10.0.0.50"
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            release: monitoring-kube-prometheus-stack
    spec.controller: k8s.io/internal-nginx
