apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr:8.1.2135 # {"$imagepolicy": "flux-system:lidarr"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
          env:
            - name: TZ
              value: America\Toronto
            - name: PGID
              value: "65536"
            - name: PUID
              value: "1026"

          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: lidarr-downloads
              mountPath: /downloads
            - name: lidarr-music
              mountPath: /music

          claimName: pvc-sonarr-config
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: pvc-lidarr-config
        - name: lidarr-downloads
          persistentVolumeClaim:
            claimName: pvc-lidarr-downloads
        - name: lidarr-music
          persistentVolumeClaim:
            claimName: pvc-lidarr-music
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: default
  labels:
    app: lidarr
spec:
  selector:
    app: lidarr
  ports:
    - name: lidarr
      port: 8686
      targetPort: 8686
  type: ClusterIP
