apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: default
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lidarr
        app.kubernetes.io/name: lidarr
        app.kubernetes.io/instance: lidarr
        app.kubernetes.io/managed-by: flux
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr:3.1.0 # {"$imagepolicy": "flux-system:lidarr"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
          env:
            - name: TZ
              value: America\Toronto
            - name: PGID
              value: "988"
            - name: PUID
              value: "977"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: lidarr-downloads
              mountPath: /downloads
            - name: lidarr-music
              mountPath: /music
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: pvc-lidarr-config
        - name: lidarr-downloads
          persistentVolumeClaim:
            claimName: pvc-media-downloads
        - name: lidarr-music
          persistentVolumeClaim:
            claimName: pvc-media-music
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: default
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app: lidarr
  ports:
    - name: lidarr
      port: 8686
      targetPort: 8686
  type: ClusterIP
