---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  targetNamespace: inteldeviceplugins-system
  chart:
    spec:
      chart: intel-device-plugins-gpu
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: intel
  interval: 1m0s
