apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:4.5.0 # {"$imagepolicy": "flux-system:sabnzbd"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PGID
          value: "65536"
        - name: PUID
          value: "1028"
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: sabnzbd-downloads
          mountPath: /downloads
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-config
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: pvc-sabnzbd-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app: sabnzbd
spec:
  selector:
    app: sabnzbd
  ports:
  - name: sabnzbd
    port: 8080
    targetPort: 8080
  type: ClusterIP
