apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bodhi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
  interval: 1h0m0s
  releaseName: minecraft-bodhi
  targetNamespace: default
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2025.5.0 # {"$imagepolicy": "flux-system:minecraft:tag"}
    minecraftServer:
      eula: true
      gameMode: creative
      motd: "Welcome to Bodhi's Minecraft Server"
      type: VANILLA
      difficult: normal
      serviceType: LoadBalancer
      #loadBalancerIP: 10.0.0.35
      externalTrafficPolicy: Local
    rcon:
    persistence:
      dataDir:
        enabled: true
        existingClaim: pvc-minecraft-bodhi
