apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
  interval: 1h0m0s
  releaseName: minecraft-server
  targetNamespace: default
  values:
    imageTag: 2023.6.3 # {"$imagepolicy": "flux-system:minecraft:tag"}
    minecraftServer:
      eula: true
      difficult: normal
      serviceType: LoadBalancer
      loadBalancerIP: 10.0.0.34
      externalTrafficPolicy: Local
    rcon:
    persistence:
      dataDir:
        enabled: true
        existingClaim: pvc-minecraft
