---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minecraft
  namespace: default
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/kubernetes/minecraft
    server: 10.0.0.29

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minecraft
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: pv-minecraft
  resources:
    requests:
      storage: 1Gi

