apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: weatherflow2mqtt
  namespace: default
spec:
  encryptedData:
    STATION_ID: AgAkovlJhR2b3k1kGbwBfOkZS0W6Ydkr6LQnv4uZljPBKu7lVCC/3pUsagzpCsMPN3i97L8h6V4VVO1i0dL+tKkBvk9DuQ7uYcafgOmwdePtVFCjdqBTIprT7DV1YkC9JNGtp5oLq76rM1sBWA7aiMfpyxRBrxxSUK4SIlFi0ISjhlv8ktSFu/hImDbqhm+MFvFs6U20T6/fCE+HNBv3kbfz0IPqQa2TFWVPylVZUkeK1LGh/0ZMhcatBDMpW+a7/rCxVTsatBLimnCMrQa1WLhzRSOyHZbtx8lMzIlHL2lmNuNq5PubsG03YB745ro+8qzL/dHS8+dtkyWLWPtw5qd5eEsGY4NNl4XyLAOfu1I21hfP/iotVpUYpFHRZrJbCPLprsO8cHBKwbfIMVNzyE0pGzq/MNXHnD1LJ3YjK7bqatIyDbLCHeXf9cpO6z4icAFfPyKhsLL/Cw74rlmn8OVV36cR0BHkU2Mh+u2y1K5lZpwJcF1hv97rWLVOaptYqp0lsUmytHD+ytQ3uIw/Qpu+dpCQywwfEsNvVQ1d+tSEAROjQDPV8jpcLDE5O9kpW5LzakDjSwFb7XC8YUjFK0H8UkmIsa0nqFH4SM8mtIDnT3Jq4pbfdnSPGwycsc5TP9v9c34Adc2g2u1VLWNzaJQ0NPmrBWGN5C6ddMmdXDoozZ7W5GWKVhbyp0JknvIpXSf12JyClw==
    STATION_TOKEN: AgCDYC9BHTMHZrq3Q6i7mLy7QlUEuQ+t6fRrSErwVpLyk0ZxcBi492948DqPj4tZFikkpmXEKlyMTSieTEFD13W2IoMubx7aqvB7eErwdnUwlXev37haOl2FFJ9r+yiI1ZHqLUyHAFSDZxwQTG2ZYgKQlUoTysJs7V51bIwtrYlHH7wWqTM0f2uar9yWIoVRaLPpKJRPYL9g3twqqt/5VbYEmPVsB39kF2bcYI8sRkSDbQsNpDpHJGDmE4Uw1/XH5M7qvbFFoPCUoFmsqhs3FLrcXS0H+mKCydjQ7bhTaRsL2sb467El9ayMSvsnj0doa0U9W1gOQfOXvGK4Vr/resdXoE6cYvQ07gFgO0I7NU4evD+BJ3Q5+0vvIkEGA/EMOuihgX/LuQ4tkGdHgNYYdYvboH40j1TInG24EmXouusQYjPnGMVprORxU8maoLPREKjTazThsuhO+5JKpCVUS6ILTR22KEsxsdG4qCZopYz3HAcMcs4aZEbaviy+Dgn+58jQG5uu4Us/YDA4eIQegPTG1Fi8I4ONE9brBNnLCXCiWU7sgNNdAlxoWE0RBdxhrXEdQHyEqAGEVwvb9EF1t7SKIdloi9rEPK33aBZLtPp/5PK6xXunRlK2PcfTr9E4d/rQBmSnlZZmFG06JMIiY1Uju0k2SY5arNuRbco/hPj9XuztkrEbx/nzUeLle2Y/xWsNKUTZhTlEWw4N4Ue2sEaqVGDcGVoZ2MIFXwyQdtEnfFBkloI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: weatherflow2mqtt
      namespace: default

