apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wp-admin-exubitech
  namespace: exubitech
spec:
  encryptedData:
    wordpress-password: AgCDnDW7ggHYSZLpxGhPdEYz75i6eRnaQI5pQseUN4bgKN1/Op/S0STtom9ZdvhTWHaHCj1DseY18p0WEu35GDZY1UxY6V6BiQ0vGDYC4RXcCSiffPymG9ElhXDgMbsqTpJZ4TGXOHyQmQ+rUNC6pZcXjrdRGigz1YK/XfymoZhpT9D2QLaqPaSBxvkPDGXU/tTwllOjveKONb/qVASxnpCjjVZvqOqePy4xVDekrlAQ+QN7r/RIw5DehvLOa3do4B2w19nqkmL5ZNPHkp7hoRXScs1ysrxVqbLg6Ej+h/peucLE3YJHvtKMqmoSNrtTVy62/xyf+OdItJizy86j40WNt/GnOTXI68RVWieY6tNRvRv0nXeV+ulvCeygVRsf9PKjR8fUSsjiMOjiSuoBAAGp2Ju4mEp24/L1XfSUECrnvJ1gDX5j2BQ2nmBG9PSYaqCjh2sk52ZnQsfjeeiSpZBImeHAnL3YvxfWjpfvfBAIhcdTgJ1979Fo6TdMi9PsxIV59cA/UPn3zy/nvX0jdkBawVsHSj1vebRVfbz3cPZjYYlxlhrd7hZwYln7XH4hcjzrUsuhiCIHE86U9oJBDz2H+skAwN1UGU12ExAfrx0eTgFSjhnnHlUdpAJ7nxpiscdpWQErGLbuxe69pvJYkLW3woKB2KDrbJ5/lEpj1lv4Wc9LEqBEHALbg3Asqg8vbXQxUcqEUa1Zd+0Yrgi48B/U9PM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wp-admin-exubitech
      namespace: exubitech

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wp-mariadb-secrets
  namespace: exubitech
spec:
  encryptedData:
    mariadb-password: AgApPyKyPoSKWVzU5TNDgf27QctLy85TZhBD68gAtCO1+I++bu8kCa0M42+B1ETusYQz/FCv/NJ7TijkqhWwg0BwHhaSTn2e77zdnOCHpmulxTfnFYIy8QcQlhi5tUWA4cgdfHId9c2KyM8xI+ihP8lCVkv3FSy5n0InPA/GRsQgDScJS3KDT3LMj99/J6Mxsvv9BIlEhgvyuMS5h8wmO5k1jSvcmVw/NflJFkD0DVUlEZmQIso5/mrzxN3r2lxc9vFnkRW37G6D8xPkXedOdz8s5SXC4qNKmw6RUALOY1pZWYSquR5hwI2UpvqxPHA++eSFYdn8Ydxj9hmESzK+hlqy4DnQD6kUlj0xiygDNuxRg4HB924YMymX4M5HZz9DoO14+/nRUHg0YNUHyumDGOwXPnjMBWRMvmxsB8GGCLrWcxTQdYOm+rWPc6uJ7d6JBNj1/U8wQdRVR55Jq5ktCla8s0CKQBWg/AshcSZkbEf7Q/XiCSn/hoS8Whwq5d6RXpkzZpUcEWaI1xXLmhzvK+j+6Ck7BuHpAH6pXpl0Co2TH54CtKtH7OzTwrnGvc+Nfhe8md/8Q8zPIZ6XRFO/z55gRAZsx+HeRbIojoxyCO8SxNTiYCbHOeIe1RMziAa1QXeKdwmoG92CIU3A5sNIVg/QRNrNu8jNHRzzoDh5XiZqTVcmCHSeEkxBvvKxhKx2rzfj1WOdJx99MnAd4YieQHHl
    mariadb-replication-password: AgA++uKmZ9HJJwEZ0IfW2ynqTVV/BHvAD1LkR5hlFLZRG829It3Pl+zi9nJm1bMtiU+PAkyODcKLS24gq2UM02c53sREQ7aJ/fbl4AtgbgAkXilT5SqWwpXQEUf/0ba6+VqW7xJSQec7rEHBOJBsqEczpEiYWwxwWR1KQ3PJLwLfmuP5ImhFT7/uxJpA1mm/XwwApQebewl5W/1qkd4hdFykWA03LIUA9UBQ44BOtqKYo7D46VtQa5rH1S2kGOwKtXdLu6Z8LGaeY6l3haakKf2k7bBViagD5+vwDjgeyhFjN7s2n/q4B2H2nwHVkWobu18BGsbsEyMReHhVW/qMdXwPByBc5Qbb3O9Fu+jGihMmw9D8UfDO2tNjc23fLC0XsVA7vW1xqnd76xtfUq7GUcx2LZ8Efqx+ZpQ1HY1mEdQ/y4b0qYc7NnOmws8Z+JEGj8EkL2oNygaM8Hb/gzOepsFfGGvNRgd9ybaNR65Xyi0jVJvc7OTA6J8XMHhkPLWSevjO7ZpxORctMbTNBD97KfUx0sn86S0KV2CVfK1P4MavjGfaNFVGxHUNa/2pRtxt7tc4c0ZTcW9iJdesuwZZt7VDQ9hWLlzNMrR+lRL+0NVsWghJKYS75WOx3p/blBTbxru0zokZ5NCtHgjcm0B5KhqjeuGDhoAuvIcrN8RlJxo8zKdwsZ+1rJ6iKIvJFGdEVyTFP+XbjajRo2f0R+Y=
    mariadb-root-password: AgAVNOHGFsAjcM2agbJKr3wHD1R38aW0A/Y1BECh7jxx0LSs64s6aKpNi0pzDp2zrgCc60WUK3makGIWhbvTO36vx+5TJ7D2SCUIcHaGSCwz781yd2W3ef41wnDo/FeIRy/zgXeiuHJnwY0tXnRoTg2/6QWmNwYAZ2isDRjfNLWN4Ocs/bxYsVPX8+ij7NDt6uMi0XyO4BpMdl3vTMOXUQAHxiLuZVQWiKAT9XcZtJzKLts7Xe3jL/dGUVjUVALrrFfb1+wl01UXy3af1CdEELZU5uQ6zk/fcPYr68te532PSHe5OXH5CbOBO0y1Wokms2d9d4lKDe6ddMALnUSIz/LEdHzBTlY1d08xYMsd9TPOLerZMsF0p208XN3NmzcJOhhmRCpItRdUSzu6vo/Gb4qxZn3hVYJIcmrQr46lDarE/xSQCFcu7vegXSOON6kutwcNU1KrHo5avoGmfJ3kLDIflFDPzrteDt5Dr3Aw4OxD22Ri0wEZGwGttVDvIpUnEfPlW7xHEB9ogaruT8gmoxjrvopRWThkg/pnK3rcg/2puM4N38u720lQTOR2cPF2ghUIbxqNLIPf3no2FGwNMYVmIRsqSV2DpisypfnkO9IuXXn2lDHdhwrbksYtkLGrXi/REixJ8ChEPLy/3ilvrBujAhttCX+g50mN1J2491OvWnmgUiBWuwjJioTwodyi8giGH0TsVlulO2kN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wp-mariadb-secrets
      namespace: exubitech

