---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-exubitech-dev-wordpress
  namespace: default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/kubernetes/exubitech/dev
    server: 10.0.0.29

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-exubitech-dev-mariadb
  namespace: default
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/kubernetes/exubitech/dev/mariadb
    server: 10.0.0.29

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exubi-dev-wordpress-pvc
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-exubitech-dev-wordpress
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-exubi-wp-dev-mariadb-0
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeName: nfs-exubitech-dev-mariadb
  resources:
    requests:
      storage: 8Gi

