---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exubi-wp-stg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1h0m0s
  releaseName: exubi-wp-stg
  targetNamespace: default
  values:
    wordpressUsername: admin
    existingSecret: wp-admin-exubitech
    replicaCount: 1
    persistence:
      accessModes:
        - ReadWriteMany
      accessMode: ReadWriteMany
      existingClaim: "exubi-stg-wordpress-pvc"
      storageclass: "nfs"
      size: 10Gi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
    customHTAccessCM: wordpress-cm

    ingress:
      enabled: true
      certManager: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        nginx.org/server-snippets: |
          absolute_redirect off;
          port_in_redirect off;

      ingressClassName: nginx
      tls: true
      hostname: "staging.exubitech.com"

    mariadb:
      auth:
        existingSecret: "wp-mariadb-secrets"
        username: "exubitech"
        database: "exubitech"
      primary:
        persistence:
          storageClass: "nfs"
          size: 8Gi
