---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exubi-wp-prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1h0m0s
  releaseName: exubi-wp-prod
  targetNamespace: exubitech
  values:
    wordpressUsername: admin
    existingSecret: wp-admin-exubitech
    replicaCount: 1
    persistence:
      accessModes:
        - ReadWriteMany
      accessMode: ReadWriteMany
      existingClaim: "exubi-prod-wordpress-pvc"
      storageclass: "nfs"
      size: 10Gi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetMemory: 75

    customHTAccessCM: wordpress-cm

    ingress:
      enabled: true
      ingressClassName: nginx
      certManager: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.org/server-snippets: |
          location / {
            absolute_redirect off;
            port_in_redirect off;
          }
        nginx.org/location-snippets: |
            absolute_redirect off;
            port_in_redirect off;

      tls: true
      hostname: "www.exubitech.com"
      extraHosts:
        - name: exubitech.com
          path: /
      extraTls:
        - hosts:
            - exubitech.com

    mariadb:
      auth:
        existingSecret: "wp-mariadb-secrets"
        username: "exubitech"
        database: "exubitech"
      primary:
        persistence:
          storageClass: "nfs"
          size: 8Gi
