apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
spec:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
  - hosts:
    - "staging.exubitech.com"
    - "www.exubitech.com"
    secretName: tls-secret
  rules:
  - host: "nginx.rees.ca"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 8080
