apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    managed-by: flux
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: internal-nginx
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: exubitech
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    managed-by: flux

---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  labels:
    managed-by: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    managed-by: flux
