---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  releaseName: web-server
  targetNamespace: default

