---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgBgGHYo4Lh7yLRm9Nwi+N8zT22xzOrv+5UtqRQEY0sSkSKHkIuCVkCZ70Prj7o7PF2UsRX1QtF4Xu7IBLlr1J3c+SK1rAlIOpoukylEExpgJ+RJA9xhsbcT+k/XwUu014rB0H9PF/UThJwuudPlyJULOsNz/iDz0fW6AhQMOF2SjAy4DSjlkyMhtZQ3Mmc1hXgIyMINujjwqQDkpT9zyxWWpX021wBrgEsdmo7Xgl8SJ59f0MpDrAwmsKDHo7144zTNkJFdTGu8hdmCyqDJQs8VWu4AJZZUAh2SADEQdFT6LXBYvC1S8rBq7hy4nLhCSt4mUyFoJyA7kVqVhW7jQoYJJTgBEX7cvgskfcn5+1mPFr2x0d5cXcnJoGpbpooWqIss4i/zulIEGqQYK9f7ycWa6PQbeGxndSiaee+SXoG8aCExaNhnVmFRxm98muTeUIIVt6YvOh/CrnI1ny6DjhpsueyRU22fjU6AVFhI3iBsvL7dmZcogffJ3pZs+rB11xOTOkT1to2VNsvwXOS98Zpqzveu5FrVYCqkYLWq/4erX3TEF1h4cB/C7OyeGGT3WXNgb9/hOpodU1K6obML59jwcJtXdpIscaNJ1oh5TKq9vFPKW96ac1Hxbeyia240iDRMmll5t/oNh/tlNE+q4bakGFm0JP4I6hZCBIXHQ/PLUh4SLoNIuv7J85qziUvcTCQr1KqOslZthFgt7aBQnUU=
    CIFS_USERNAME: AgAsqU35sG33z+K0rfE8SWxJFx3ijHX6nMkhV3qrlgX+MwVB7ATs7OuPA/7Ga+UcfOZ+Ac8K5djfYM999LzKi+aSk2ZBZk3cUIdcxoyv0WDw7r7VPEEZza9tALs+ow3CDZL27hg9zFfwQQWlvFQgDL5XnJwqVVQzmzfRRMBz8xkgzgn2Vl5U6ltSUjcI7lzqTdMYbQ1TYsbA8J+j3HaRIniQI1E7AhR3yuSXXqBIZYhUg6v6rJm4FSezMC0Ni7mT3ZK3G48cdLfwXoDkrIKTKPDJ88hBs3tNzenWEHINUWIxPSbzqCDbUsvsDUpSF+BDxLcypsjnG6AgmW/ryI6s7vPE/NhTijIPmv80E3TyTB54C+is4ihYf6HHx5cRPLQWxYLSNABzCfM3Gz/Hjoii6qe9y/IHudmZ3yQNjAw7u5NfMgt6IzaW0uSRLu0aboonEfcNHy25ul5Qtjzc/oNkmD9PDekf61cYoJLJDaj4ARnsBFSVe7VC+tGGpIo+uRUVtEnrzhMk3rR8Lh669PqOLcbBbd4tvI9CxZDUoekE1Hud+k52STSsklB0q3buK6nW5SDjdmQ7D2LmXBODzgNBfzUalgIAqgc+FOG3kMHe5SUv/hrEQbXd6KrwneQqwtetrTrDws6EW52Gb+IPWHKHZEPqqoTeza2kCtJQnbl3MP5cjX5xEwP62KTy8VQx6iA+NsOS5JRwiNwlbw==
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
