apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgAuKA81zMW3TO+YmqnA7pHnWbF5RV8R7YTkgNhD9kOzWyFYPDGF34fNXnkcb/qim0OGSArPgF7ImFdUa4Y81ZIZe2ONH5XMgLj7NkcCktUF86pPS0O3sA/m3RHXIjAYZ9fS+Uc06tcBXveMlDCc2tekqZJSIPTG+6/81fNCZBWhTHD1gnYsFMzTeCjyhpJlq03M49SOjJofzslPrdCVLImrVQNLs/s+tXhcs6dy/qht2EdWBIYgV9bhh7vEv1BaBogdfaXxx9nH1ULba6ydJBryoi6MxA4ByNPBgweF0pFuJXKPbd5vxOOIloMBzNeSGzt8OCP9bJErt4vVuv4B9tJQLXSzuaDarU6uroAdH8vv6qYbm3sErAdyv8VtOkw08aBAT1G+ojgxCUfpyAU4Gzi2Bnh//j6DyTsBeF+su0lKbJsAtiAdoqzLUAjK3G2rvXzp6m3TnpxJ9cW1TIKC97Bl++6OpdCF4aN7DOoew/rYtRH9/+vVo1PtU5/OHfnfC6NYEOKzMHDYR3TxIoFbBqJAumKnp1AUOYCLbJqZbIZ5XS3fqzQ92+7qkVaQvFfd0uKvXxeKLZcRtMJmAAYHVnPKtCe4Oh2uGjtLVwCHvJfaREBzu9uLgi6njtBmc3pw48uD4tsxjX/desEP/T3muu+sfalRszmzie0Hj1/mvrpsKXdooy37Fc0jo1Qr8ce8Hn6b47pJNb8GF3OGx9SX182jvu3jByIONp/04HsUfUN+8G9gz5xM/eupS4n7iQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: longhorn-basic-auth
      namespace: longhorn-system

