apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s
  releaseName: home-assistant
  targetNamespace: default
  values:
    image:
      repository: homeassistant/home-assistant # {"$imagepolicy": "flux-system:homeassistant:name"}
      tag: 2022.6.1 # {"$imagepolicy": "flux-system:homeassistant:tag"}
    env:
      TZ: America/Toronto
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    securityContext:
      privileged: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.org/websocket-services: home-assistant
        hosts:
        - host: ha.rees.ca
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
        tls:
        - hosts:
          - ha.rees.ca
          secretName: ha-tls-secret
    persistence:
      config:
        enabled: true
        existingClaim: pvc-homeassistant
    metrics:
      enabled: true
      prometheusRule:
        rules:
        - alert: HomeAssistantAbsent
          annotations:
            description: Home Assistant has disappeared from Prometheus service discovery.
            summary: Home Assistant is down.
          expr: |
            absent(up{job=~".*home-assistant.*"} == 1)
          for: 5m
          labels:
            severity: critical
