---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-home-assistant-config
  namespace: default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/kubernetes/homeassistant
    server: 10.0.0.29

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-home-assistant-config
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: pv-home-assistant-config
  resources:
    requests:
      storage: 10Gi

