---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
  interval: 1h0m0s
  releaseName: frigate
  targetNamespace: default
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # PCI attached Coral AI Accelerator
            - key: feature.node.kubernetes.io/pci-0880_1ac1.present
              operator: In
              values: 
              - "true"
          - matchExpressions:
            # USB attached Coral AI Accelerator
            - key: feature.node.kubernetes.io/usb-fe_1a6e_089a.present
              operator: In
              values:
              - "true"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-url: https://auth.rees.ca/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.rees.ca/oauth2/start?rd=$scheme://$best_http_host$request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Preferred-Username"
        nginx.org/proxy-read-timeout: "3600"
        nginx.org/proxy-send-timeout: "3600"
        nginx.org/websocket-services: "frigate"

      tls:
        - secretName: frigate-tls
          hosts:
            - frigate.rees.ca

      hosts:
       - host: frigate.rees.ca
         paths:
           - '/'

    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.244

    extraVolumes:
      - name: frigate-data
        persistentVolumeClaim:
          claimName: pvc-frigate-data
      - name: frigate-recording
        persistentVolumeClaim:
          claimName: pvc-frigate-recording
        
      - name: frigate-clips
        persistentVolumeClaim:
          claimName: pvc-frigate-clips
        

    extraVolumeMounts:
      - mountPath: /media/frigate
        name: frigate-data
      - mountPath: /media/frigate/recordings
        name: frigate-recording
      - mountPath: /media/frigate/clips
        name: frigate-clips

    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
      - 1001

    env:
      TZ: "Canada/Eastern"

    envFromSecrets:
    - frigate-secret

    coral:
      enabled: true

    config: |
      mqtt:
        host: mosquitto
        port: 1883
        topic_prefix: frigate
        client_id: frigate
        stats_interval: 60

      detectors:
         coral:
           type: edgetpu
           device: pci

      birdseye:
        mode: motion

      ffmpeg:
        output_args:
          record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        hwaccel_args:
          - -hwaccel
          - qsv
          - -qsv_device
          - /dev/dri/renderD128

      record:
        enabled: true

      snapshots:
        enabled: true
        bounding_box: false

      cameras:
        frontdoor:
          ffmpeg:
            output_args:
              record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
              rtmp: -c:v copy -f flv -ar 44100 -c:a aac
            inputs:
              - path: rtsps://10.255.255.1:7441/lq1LjWSSI6BVF72F?enableSrtp
                roles:
                  - detect
                  - rtmp
              - path: rtsps://10.255.255.1:7441/wEpNW7kCLkOmj5K5?enableSrtp
                roles:
                  - record
          detect:
            width: 960
            height: 720
            fps: 6

          record:
            enabled: true
          objects:
            track:
              - person
              - cat
              - dog

          mqtt:
            crop: False
            height: 720

        driveway:
          ffmpeg:
            inputs:
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.30:554/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.30:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.30:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1280
            height: 720
            fps: 5

          objects:
            track:
              - person
              - cat
              - dog

          mqtt:
            crop: False
            height: 720

        testcam:
          ffmpeg:
            inputs:
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.20:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
                  - rtmp
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.20:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - detect
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1920
            height: 536
            fps: 10

          objects:
            track:
              - person
              - cat
              - dog

          mqtt:
            crop: False
            height: 1440


        backyard:
          ffmpeg:
            inputs:
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.26:554/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.26:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.26:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1280
            height: 720
            fps: 5

          objects:
            track:
              - person
              - cat
              - dog

        sideyard:
          ffmpeg:
            inputs:
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.28:554/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.28:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.28:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1280
            height: 720
            fps: 5

          objects:
            track:
              - person
              - cat
              - dog

        shed:
          ffmpeg:
            inputs:
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.27:554/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.27:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
              - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@172.31.2.27:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1280
            height: 720
            fps: 5

          objects:
            track:
              - person
              - cat
              - dog

        kid1:
          ffmpeg:
            inputs:
              - path: rtsp://wyzebridge.default.svc.cluster.local:8554/bodhi-cam
                roles:
                  - detect
                  - record
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1920
            height: 1080
            fps: 5

          objects:
            track:
              - person

        kid2:
          ffmpeg:
            inputs:
              - path: rtsp://wyzebridge.default.svc.cluster.local:8554/rocky-cam
                roles:
                  - detect
                  - record
                  - rtmp
          record:
            enabled: true
            retain:
              days: 3

          detect:
            width: 1920
            height: 1080
            fps: 5

          objects:
            track:
              - person
