apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgChlllhw8YYJHmPDfPJtPzXxIBRit+FFR48gz7wZVS1L2djoJ6l4yzi9pgtEGI387k5IZcNKx84aE2BdDGghjNbpyVGvfzqoYTF/0lkjyqWottOmS2VYQAD90kod0c5srYCmq0UMCbyjjUi4lWAOWv5aEaArYN0r4tXVU7iTWQd0H5YkALgHnkd0U+INoxiZr5Gx74FQKFmzX8Zg0/ud2otXP20mALL9KTvyHVoWDq72Hl6WPAoSuzRWHFahWP4QYDZVrIaqYIi7kNlP50SENZLkgTnnL6tUIFSdndN1T6+ZLTCO/eA+UOuD366Yv4qd5WnMlFKBQpC4dJe8jh7YkTwUFeJTPB8GsjwAZC7WBQIxIu7kbU37b27KdBPDPRymNFMOyGi8u2bV6him7QU1ChDe6YTek7vfnddBJz/dCy6rzhNkRmaz8WbCb6FbhNqsD+wL3lTEL5wkiTFwgSoFmjIvDSJpA0ch379D91Lqk8eSxL4bghChSKCjqBuQuiUoZVcDANPSkLhTtwW59B8OvpwnNZTF4Ut5l2MzDpnFUi9c3kfnhqVtQRIZQkBjBx48aZ681X6yMhYl+6xK82vupc/x8u8pZxnEaFNtrdE1hyz8xFhiXJTX0gUGHxYUt1wg2p9rF88ioRrB7H9ulbEKxxpUCybOjQqxMj8BK2EjUaB4ENTLg2rMGLB8kqmENMnLwDqgF7/EwhEk2A=
    FRIGATE_WYZE_RTSP_PASSWORD: AgBN22Fulh/If+Wtgf2srYtjYaEOJNMCLb0LVxgZg36k24rlU8ApK+cN7dUOYpkx943IECOksfH4tA9y0HsRxW0EXqk6PxBWAJfD74mdzHgYa564QrKZwZds3V968fyZhaDsxB/s2Vx/Qj87VCHHP5GlummFZ2RUaraovz0uTozUqCZENab7Kt2K/wjYZZK/f5a5RPKQS2UqgPgoYvw9yywAqvHOynKHw0s4oN9xO6Zqbk58Oba0UBnAsj2ANqeQqh0dETtVXoKCd8lTYhcCrfohHXh4aA58czrSBUfzpb9XvzLKqu/3OAFJNaIr0ZBJsN/fURZBNZN6KPgEVoqtBv19UTDPdFZFsIFs6uxVVvDqGVUjcLAx1nspNzVGBa7rmbglCuMg5JjzQ1oEs+d1NhRePnnjl1dgM606s5hJI21hE0IPz8t/5Nlcw/sBWQJlm2glFURWqkLlnAY55DMBod1nfT3zGyP4ZXLpJsoQHatOUk43wVqopiq7o/KXEs3agmwXvk6sVVd51pHSuIcPqIcPEzYrLTymBjL8E2vkeB8z58gyt01N8zgOy345PaL8FHgOtewwByxNFCCVrEioMzoI8Dc9BuovF5aXwo1LLkiaMxVpJCeIvz/CNoLB5XvDstonC7blZh6NrkQ3zy1KNC38zmDWgmYzOFPcvBb/zVpmTTSlHsk746ahOlQxIW/cV6tuv8DFALo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default
