apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgBXo0PZMCJwemQKHJPEcW4wnEcdGZnZ+69Uj/Hmoi4gTHWPpYbQbhyzLZDE/WJkr1fSdS/tZG4Imn6N7VPCsD9f9tkV9zhWCywLpju8ZhZFiKZSptuEcpk0nXCqNT8Z/5g3vQfpg+nbXceVDMKG1pW8JZphYZ/mVzXlXJbukyNlW7sHqbJX0sO03bHvtxoFFfCvy+2+eaOp1/YNCwqrTi/w9bYW5kX2eTU/w9qJhYDrTi/WbxsXbyAVR/iwwarbM/Bt5h3bckbRK/2CENIejuzR49zaiZYd1sSc9KyzgxbcCRbzGAOKs+7GIBV6t5ona8DKHv8IgWgw2PngPbgr5R0Xj6QUm257TpACQf4yh7VvHudJKFsSsp3han99+lpW9iAXxkMy/GZVRkdq1uqIE10OcfaUbTZE8hCbM4LjsX2bRZRSdUdxXa1VEF4eBR9EI2fXPTzs3I5k6E7BCr3bUXWuoBrLJNx+6DsfSKS2+fOoCcdiKSXxs6HYj0oYGAzQTnx1DDzsy9KYXf1gfDapnHvsirfJIIEy+40EaoRN/ONCdJRoZlWuHY3v/KLfQdeDBTeIjKcZ+/GJTDMMDDgPgsSoUWg+LyqqrQQml/ZRXNeXE/o2uFZ3KRmyL+gfKJuUgBLFGxWAqXdPiCzC3iz4vEtLgz7Q16hr/cNGUtbr3/zaC3vr4BkeKUukilo8y/85tLKZMqgs7pzasg4=
    FRIGATE_WYZE_RTSP_PASSWORD: AgBbUYTmognPK3jIewYoZKRswddlCBloruqzQD6kfqQZ5cAoG0AmcXF48wzjcoPFyyy4/JnTVpXjW2kToyPURkJaNXBId19WtgGJztXeDuhrYRFeDKkPEGm/XXT5GYRgoyE/4AHX1vsJSTS9fr/pgKveDGJylRae7gAk5X2VtLlNafo263K+0935s+lEop7E+gKjRBTdbLdH9Pcw7+J9c0qacmjf+8gaUts5XdJRNBSNySewK83u7FPkchvmeIRcA1R0gidiZS+apI/n9V8juim4S9Zs5XQ6HLEm3CN487Exk34pl/OmEyEgRtkoAC4Al4B6jdwlhAwmyXIpwNKu+19Z8n8PwCRT1/sYMkaAwaPeyb+bi3KEk2HGndDxgltRMDUGdW9jideF9vAlzPuZNvjxxIDfSQ6ImdH7rT6a2FFA0GqotevcJLa4IvY/u/CcrGU6oOqByOdjiN2qMnCg62HlRYpAUDDSw3eTqKnSxpbzclHJjUjnnzQJHvc00CksxmjyRSkvODcq8PWd1xPda4yMhOrI1PmybETdEqNdaCFVrrlFeT0NWHGFKztr/2/citVCEFzcewQuVlGpki8+hb7TuRXye3yQrrASwt7Qo/veDAw4AE+sUrCxA8h2orGO2XSdzWPEy+tQrPjp0t0SK0gntCT4g6pLTifkDphhGdwhXMrZAYZVbhzqhi0FedzzJIm/Y3fxVas=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default

