apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
  interval: 1h0m0s
  releaseName: frigate
  targetNamespace: default
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: "0.12.1" # {"$imagepolicy": "flux-system:frigate:tag"}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # PCI attached Coral AI Accelerator
            - key: feature.node.kubernetes.io/pci-0880_1ac1.present
              operator: In
              values:
              - "true"
          - matchExpressions:
            # USB attached Coral AI Accelerator
            - key: feature.node.kubernetes.io/usb-fe_1a6e_089a.present
              operator: In
              values:
              - "true"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.244
    extraVolumes:
    - name: frigate-data
      persistentVolumeClaim:
        claimName: pvc-frigate-data
    - name: frigate-recording
      persistentVolumeClaim:
        claimName: pvc-frigate-recording
    - name: frigate-clips
      persistentVolumeClaim:
        claimName: pvc-frigate-clips
    extraVolumeMounts:
    - mountPath: /media/frigate
      name: frigate-data
    - mountPath: /media/frigate/recordings
      name: frigate-recording
    - mountPath: /media/frigate/clips
      name: frigate-clips
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
      - 1001
    env:
      TZ: "Canada/Eastern"
    envFromSecrets:
    - frigate-secret
    coral:
      enabled: true
