apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgChlllhw8YYJHmPDfPJtPzXxIBRit+FFR48gz7wZVS1L2djoJ6l4yzi9pgtEGI387k5IZcNKx84aE2BdDGghjNbpyVGvfzqoYTF/0lkjyqWottOmS2VYQAD90kod0c5srYCmq0UMCbyjjUi4lWAOWv5aEaArYN0r4tXVU7iTWQd0H5YkALgHnkd0U+INoxiZr5Gx74FQKFmzX8Zg0/ud2otXP20mALL9KTvyHVoWDq72Hl6WPAoSuzRWHFahWP4QYDZVrIaqYIi7kNlP50SENZLkgTnnL6tUIFSdndN1T6+ZLTCO/eA+UOuD366Yv4qd5WnMlFKBQpC4dJe8jh7YkTwUFeJTPB8GsjwAZC7WBQIxIu7kbU37b27KdBPDPRymNFMOyGi8u2bV6him7QU1ChDe6YTek7vfnddBJz/dCy6rzhNkRmaz8WbCb6FbhNqsD+wL3lTEL5wkiTFwgSoFmjIvDSJpA0ch379D91Lqk8eSxL4bghChSKCjqBuQuiUoZVcDANPSkLhTtwW59B8OvpwnNZTF4Ut5l2MzDpnFUi9c3kfnhqVtQRIZQkBjBx48aZ681X6yMhYl+6xK82vupc/x8u8pZxnEaFNtrdE1hyz8xFhiXJTX0gUGHxYUt1wg2p9rF88ioRrB7H9ulbEKxxpUCybOjQqxMj8BK2EjUaB4ENTLg2rMGLB8kqmENMnLwDqgF7/EwhEk2A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default

