apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:2.0.19 # {"$imagepolicy": "flux-system:mosquitto"}
        imagePullPolicy: Always
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/configinc
          name: configinc
        - mountPath: /mosquitto/data
          name: data
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-config
          subPath: mosquitto.conf
      restartPolicy: Always
      volumes:
      - name: configinc
        persistentVolumeClaim:
          claimName: pvc-mosquitto-configinc
      - name: data
        persistentVolumeClaim:
          claimName: pvc-mosquitto-data
      - configMap:
          defaultMode: 420
          name: mosquitto-config
        name: mosquitto-config
