apiVersion: v1
data:
  mosquitto.conf: |
    per_listener_settings false
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data
    autosave_interval 1800
    include_dir /mosquitto/configinc
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  name: mosquitto-config
  namespace: default
