apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:4.0.14 # {"$imagepolicy": "flux-system:sonarr"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
        env:
        - name: PGID
          value: "988"
        - name: PUID
          value: "977"
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: sonarr-downloads
          mountPath: /downloads
        - name: sonarr-tv
          mountPath: /tv
        - name: sonarr-videos
          mountPath: /videos
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: pvc-sonarr-config
      - name: sonarr-downloads
        persistentVolumeClaim:
          claimName: pvc-media-downloads
      - name: sonarr-videos
        persistentVolumeClaim:
          claimName: pvc-media-videos
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: default
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
  - name: sonarr
    port: 8989
    targetPort: 8989
  type: ClusterIP
