---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plexclaim-secret
  namespace: media
spec:
  encryptedData:
    PLEX_CLAIM: AgB75z+uZ0bQpKrMSwjtxHszXksGT/S+Zdw/zRXqwDcDE50dvOu1evVq6Esyd5QAxWah+WA8/uyyqHn3bfvfOBynDqkYVrkgzsokhuAoghVz6RDhKQROBFYBmBUHUEN1tID82zbXIKaegZNdNgnu/DFA2pMYt9HckjW8K0DgqqehdJ12SqafTma7Yw9a9yUcRtDatq/UFkBJriDRvH6WgqebpgrQxAc8SDz71fUtsTHfnnWMqFVDj6TLfYDndQ9ZR8ZfXpwkdBDCcpgK3/rNTcvidm4cosohJBL0EzKnvfXtxyD9OZ1xRElceZZ7WunhxAW/5HT5eZSQ2rQZl/IUO+LmNauoBiKEwKn19aVXZptUcI2mejKZUWtdhpUiz1fAY3NFpNlgxhQrq5vKVjtRAorM7AyXItixW5kq4vzOdEushFTmIY+Xugis9+z+jyTUMn+rMcgmrDTuTU/6QK1F/bz2AVBxLZTycpuFk9a1I8YzhzBX7a4s8h5lxCNq0fGIw97i/O50L0+Dla/LjDype069csB+gmLD5zfqV+2T/svj9XEgVTcffvXAu70a458u8kh3fTnozAG0cpyiV8CCseU+NUtiMp1xKAHS1Bm2J6wD6e3ZJpGAyIbIO9wgx7lL88JnmaST4o7UH9fop0RJQ9vSOjROXJp6qbzKlG13+0PoFRZmVsICvybU+taeTe3ke7TavlCmxF+hHF1dXfUWetQnf6UFW9ELFVayJg==
  template:
    metadata:
      name: plexclaim-secret
      namespace: media
    type: Opaque
