---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: utilities
spec:
  encryptedData:
    .dockerconfigjson: AgCONvhG0UB7pDZA1ntU5KNAAXYpjfnramzLbz7YOc/m/sS67phbUcIo8X4N4wfmkXxYO5ib1GZkrvZyEjMPasKL1cXtb+Li9yGfxnVIS3ihOjjph6Q9531p5IQ44Ap0AwsRMNspZG0flmTt9SSfCHBLoJC+vNEt39j4nQ8dNOXju7ZCqHJ5ntQgfOFwWMouLhRUTJZYKOkxCkovv/pv7BWnZ7XbkDfxrFzkimvtaVqVDoK9q5TmQN5dG/OCZkM/ex3IjYDGAH3vV8bJTLoIXmQNNIPqfO1nJMTVRRAXcK9WTOQ9LHopb6yBHWYnhrm6uyfFkxwtnszvqECnnvk0KTZWExWe/SouiHfxrNzr5VP2G/2Ha6mTQRB7zktm1If8fucd/+LJ+pLFutZGsGGo9kQhFw/hD1PMSyFKZ6Fat/SXaF+A6wlju5j4KAGqb3CEESPYK8OtW1I9w91qRbm76WgnkkRoZUQoRzP9pxREnKWK51SCJVxBerbssLZB+0gId7oh0D0a4gtMQYNluMGeu7J3mBfhwO55M9rGwTIoPdxWJEHqSV9SPiFAm3yIBivgYDhxxCG3rPbWIgeHgBJwhg10u3O/TwHZBIUJLTdLP807+0oMXJAI5RKjgt8c/dG9ZhhSw88X5F7tuylIJiXVu43gJPmavcyQJI2u2sFHfbHAi7Lf+3toXTE7lLTFvXkGTXvMKUjCoUb/O2N2QY/9+JuMLQyztNoMXAZ+/ZdIB910Id8O3JYJkShFBbK++HyLpFL78HtQZSlSJdmsoi2m6nBd1ch7qltB6bX1Axxh2diPfMV5JzY/fvaaQfMltLe3j6SYNTXYdezI/mjPsvftOH708vsdJz+pvpDHE+Z3GJ+qFOuPRUSfx8DzqbQLH3U5meF5QHKHp09CAEWxxPh40KWytXG1DKtpk7DzYve2TJv1AR2Ajkyvq4COvLgXuFsuJ1nTLqL1hAz/rPzVp9wNvO+027pyx/5AmykM4730VtQ=
  template:
    metadata:
      name: dockerhub-secret
      namespace: utilities
    type: kubernetes.io/dockerconfigjson
