---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: intel-gpu-plugin
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "50m"
        memory: "128Mi"
      type: Container
