---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 1h0m0s
  targetNamespace: kube-system
  values:
    bpf:
      hostLegacyRouting: false
    cluster:
      id: 0
      name: kubernetes
    cni:
      customConf: false
      uninstall: false
    encryption:
      nodeEncryption: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.245.0.0/16
    k8sServiceHost: k8s-cluster.rees.ca
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      replicas: 1
      prometheus:
        enabled: true
      unmanagedPodWatcher:
        restart: true
    policyEnforcementMode: default
    prometheus:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: internal-nginx
          hosts:
            - hubble.rees.ca


    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    routingMode: tunnel
    tunnelProtocol: vxlan
    tunnelPort: 8472
