---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-auth
  namespace: automation
spec:
  encryptedData:
    admin-password: AgAqm69iPgvHWhc6TPBaDtkuYMuGutKCysrTEPW/d6tE+UQgMJ04VEQk6WZc8sFbc17+/0o5OWqlo7m7L4dolxsXhptlqs8vf/mJ3WVmE6noSu++UnjMP2yhYTvF+sFo4krJjjfHsWdaTA+Ed9yTBUlKrkY+8AmkLG7toLy+fUcPzVOmnOvaJy61ZaVGKGLp0aRDqdZXwu6qqb1QIDq+SAmhUSI9O49XIO76mVKFdgGtQZi9z/q5B7M79yS2Mcpyyj6dbFWZ0x8NtUtl6qcFzO9CB3p/6PxUBVh0RIyOR3o9ihpfB9+ngYXdbfEqO2VfZoaF7LQFdUYdXHUXp37A39eHxEdLhYJurdL0+bNO2+7RAUuUgPTRdatCFZ2VCug/EAwu2VClBMgwxIA9ZQcYh/NVb/CC+yXKPm2dzAJBuwJGrHcEtr2WGvHnmsUsDcksqGckkCV6VFHa+2+rk/Afl1uf3otX/NOCXd8oWKs3ub0vihwvDAN8wNh9/cjVssVqFvXGwN7ufW3xqnJh3dpOJZLmrrm/1AmPw9IujSfRH70mvAH4olXbnLHwYhzFVpd+3+VcsafWJTcbhW6Pq2Wa/OqjhEQ/6irVHQPmGol/1s5NDiC1LWlBlxsSlnk84jHUHQ17wnzHnYUCWUdKg8kTyRBSDqCYKuGThn4AbZ0RMVfpITH3OBJbM8GhvC5SpuaWZOMV4oK22eTWmQ==
    admin-token: AgB0aC9e7KUelvsC8H5g/8u05bcRX+OWWcXnij6JLdIg++FFJSDNIlzk/gRKaxtkIluHJO90zHaUu8gmzm3RFPnTPAIRwe1W3qdFxNi6XVtLpGX4R7XzKZdnUooXcbwmOG/xB1dKy6dtewn/B+KnaVKWqAzF9azhjEjdm6hXMNcy6kpOA6uVNiDvtczTHWN/fG+aafyq5skfAGUEfM3BlVRSuutyNXilWzDzWt22+fP6ge7KOo3Dcf3+7K/ptZ+BltQj1opBvblkp3ljzvccktznxcwZNtTgQJ33zXT+W9t5FgtUO0NWpVAH8uChwLVyq+zDYFN9UZjMBTrlEO3dI7PSvR/bm70uAm4uynupPA0GdL65ppE/6aGdE/wVk4XGuTRUx3lCR1jr1YM9LpQbPD1V8RDQMx5nw7KRIdRSt9d6O4w+3sWtoJkVKn76TvBfd8TjqBDsFI8W2nlLk8C5Zpl0IAgyYD0q4qR15THX5cyqt000MFKyur4MkGEInTSBSIriwfmuxIrXera9xrLINSOhys44q8ZlOcEbPJWJaobSHRmiGJ7xr43PaD6GtKzhQYGUnZ8FTo5mtzryXsLnxIgvdxabW4OxmOmtejr/dORW9UG94e9fC8M7u5WiSS7uAS8EpS9lDKcdFaYhhd7YqyYo1RNmkTLnqKiy1an9TdjV+s1tCxdu7G0ouwlvhxJAeiDB1UNJRZ+0Fw==
  template:
    metadata:
      name: influxdb-auth
      namespace: automation
    type: Opaque
