---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: flux-system
spec:
  chart:
    spec:
      chart: influxdb2
      sourceRef:
        kind: HelmRepository
        name: influxdata
  interval: 1h0m0s
  releaseName: influxdb2
  targetNamespace: default

  values:
    adminUser:
      organization: "Rees"
      existingSecret: influxdb-auth

    persistence:
      enabled: true
      storageClass: "longhorn-static"
      size: 50Gi

    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hostname: influxdb.rees.ca


