---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ombi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ombi
  policy:
    semver:
      range: '>= 4.7.0'
