---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ombi
  namespace: flux-system
spec:
  image: linuxserver/ombi
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: lidarr
  namespace: flux-system
spec:
  image: linuxserver/lidarr
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  image: linuxserver/sabnzbd
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: sonarr
  namespace: flux-system
spec:
  image: linuxserver/sonarr
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: radarr
  namespace: flux-system
spec:
  image: linuxserver/radarr
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  image: pihole/pihole
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  image: homeassistant/home-assistant
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: plexinc/pms-docker
  interval: 30m0s
