---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ombi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ombi
  policy:
    semver:
      range: '>= 4.7.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: lidarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
  policy:
    semver:
      range: '>= 0.8.1 <= 6.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sabnzbd
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: radarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pihole
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pihole
  filterTags:
    pattern: '^(?P<major>[2-9][0-9][2-9][0-9])\.(?P<minor>[0-9][0-9])\.(?P<patch>0|[0-9]\d*)$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homeassistant
  policy:
    semver:
      range: '>= 2021.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<major>0|[0-9]\d*)\.(?P<minor>[0-9][0-9])\.(?P<patch>0|[0-9]\d*)\.(?P<something>0|[0-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: minecraft
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: minecraft
  policy:
    semver:
      range: '>= 2021.12.0'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: double-take
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: double-take
  policy:
    semver:
      range: '>= 1.12.0'


---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
  policy:
    semver:
      range: '>= 1.26.0'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: zwavejs2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zwavejs2mqtt
  policy:
    semver:
      range: '>= 6.00.0'


---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wyzebridge
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wyzebridge
  policy:
    semver:
      range: '>= 1.9.0'


---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: weatherflow2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: weatherflow2mqtt
  policy:
    semver:
      range: '>= 3.1.2'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frigate
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frigate
  policy:
    semver:
      range: '>= 0.11.0'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mealie
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: '>= 1.3.2'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: '>= 1.30.0'


---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mosquitto
  policy:
    semver:
      range: '>= 2.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: esphome
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: esphome
  policy:
    semver:
      range: '>= 2024.9.0'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: immich-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-server
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: immich-machine-learning
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-machine-learning
  filterTags:
    pattern: '^v(\d+\.\d+\.\d+)-cuda$'
    extract: '$1'
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: redis
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: redis
  filterTags:
    pattern: '^(\d+\.\d+\.\d+)-alpine$'
    extract: '$1'
  policy:
    semver:
      range: '>= 6.2.0'
