---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: botkube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: botkube
  interval: 1m0s
  targetNamespace: monitoring

  values:
    existingCommunicationsSecretName: "botkube-commconfig-secret"
    ingress:
      create: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      host: botkube.rees.ca
      tls:
        enabled: true
        secretName: botkube-tls-secret

    settings:
      clusterName: production
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring-kube-prometheus-stack

    extraEnv:
      - name: meep
        valueFrom:
          secretKeyRef:
            name: botkube-secret
            key: appPassword
      - name: BOTKUBE_COMMUNICATIONS_DEFAULT-GROUP_TEAMS_APP__PASSWORD
        valueFrom:
          secretKeyRef:
            name: botkube-secret
            key: appPassword

      - name: COMMUNICATIONS__TEAMS_APP__PASSWORD
        valueFrom:
          secretKeyRef:
            name: botkube-secret
            key: appPassword

      - name: BOTKUBE_COMMUNICATIONS_SOCKET__SLACK_BOT__TOKEN
        valueFrom:
          secretKeyRef:
            name: botkube-secret
            key: appPassword
