---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: botkube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: botkube
  interval: 1m0s
  targetNamespace: monitoring

  values:
    #existingCommunicationsSecretName: "botkube-commconfig-secret"
    communications:
      'default-group':
        teams:
          enabled: true
          #messagePath: /bots/teams/v1/messages
          appID: e7459075-87f3-42cd-8014-6a13ad3ee08f
          appPassword: L.k8Q~WwGC.uYkWS4176QTUTdyfaDPJs5dEzgcHU

    #executors:
    #  k8s-default-tools:
    #    botkube/helm:
    #      enabled: true
    #    botkube/kubectl:
    #      enabled: true
    ingress:
      create: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      host: botkube.rees.ca
      tls:
        enabled: true
        secretName: botkube-tls-secret

    settings:
      clusterName: production
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring-kube-prometheus-stack
