---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1h0m0s
  releaseName: metrics-server
  targetNamespace: kube-system

  values:
    replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args:
      - --kubelet-insecure-tls
