---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  targetNamespace: kube-system

  values:
    replicas: 2
    apiService:
      insecureSkipTLSVerify: true
    extraArgs: 
      - --kubelet-insecure-tls
