---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 1h0m0s
  releaseName: metrics-server
  targetNamespace: kube-system

  values:
    replicas: 2

    args:
      - --kubelet-insecure-tls
