---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-radarr-downloads
  namespace: default
spec:
  capacity:
    storage: 35Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/downloads
    server: 10.0.0.29

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-downloads
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-radarr-downloads
  resources:
    requests:
      storage: 35Ti

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-radarr-movies
  namespace: default
spec:
  capacity:
    storage: 35Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/video/Movies
    server: 10.0.0.29

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-movies
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-radarr-movies
  resources:
    requests:
      storage: 35Ti

