apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:5.24.1 # {"$imagepolicy": "flux-system:radarr"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        env:
        - name: PGID
          value: "988"
        - name: PUID
          value: "977"
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: radarr-downloads
          mountPath: /downloads
        - name: radarr-videos
          mountPath: /videos
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: pvc-radarr-config
      - name: radarr-downloads
        persistentVolumeClaim:
          claimName: pvc-media-downloads
      - name: radarr-videos
        persistentVolumeClaim:
          claimName: pvc-media-videos
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878
  type: ClusterIP
