---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rsyncd-secret
  namespace: media
spec:
  encryptedData:
    RSYNC_PASS: AgB+lvnTytQa/E0QQ5+0wj1SKh7edlBleuUIm9CAcAGDc2XJYdiVWdwvYzldfnW/uPN7SBL2WWFJkPXTF1KjzPouZbEBnIP6/8q5GdqK6V5r+4dPKEl3+9I5zukdPUl78JwU8/A4PdBdIOROVpOR+Q2Fi7ZOdP8Q8w6PfW0ldLk1J+0aNh1GanSwCBxDJQsZctglWVRuZQW/1YQAvHtE8D3SN4UO5FWWFiAwHYof0DC9PJUwB4cLOJxkiWAP/Lag4NaB4T1ej0iCQZ+Ge9hxNmMepA1MXD7MwD6wfcC8VjyDM4NRzfhisHnj6EjVAPpLQL5Cjf0ZzyppBL8dy2TZDQAh3GQROIZO/GmePTOYmIU37K8ssTQ3RE8BU/r/F6iCr7MVZ3MG/HxCZKaXKZPu/qHNoJ5bEu4ysznsWWZzvfjHCZhuimiGL9ZWoyyFZ7AStRKb95DMUlINY5QFer+N17hu6h3aARD7ahatb8i/vOz4GSNCwTPNFEe+AApMSnE0AAtLzACQvc6Hd6efVgQln8410uDzW+mQC0HmEDLlhjQce1OMwdmzrPqodziULDRnKabbgclw2cne2evPtrtHsqrOLZT8n0y/qThBzFP+0hntbxm0WUTUC58u+CPLvMye7hzNE2wKRBWQRdwNr4JYtwDT/UIeGSRIaqZmzc2ch05BClz6vSXRiQUsA9u+HgEHNOqn5GJm8qd8VpBpnLLFYVNO5oY=
    RSYNC_USER: AgBAZ0TlWIpFAhyEIoGNrnOiwvb3v8v9PQIst3FyUiDMk8vE6iwAXOSFeuqT3991wUxlTH5PrBA68Pt+JYVcse8VuCg0XcNo2vQutO0wOuYL36JHZ5bAV1j/dwMOfN9ffPjpbjVGw3kgSXxc0PZ0F9W+R1+ZdVQUbKGprBAfx7vNXI/rRpSP5Qoq7Xjfa2IwkQeZKjLBucyg2KHsQuZb1QQCaecxxOTf4aHtyvzpHYuzlMZAT8ZO+p607J7INneqPfqn3oEkQdfLnSpNu0Tk/K2C5Cc7boZaYPzG5tJN8wrwWFkbBBrKoKU5oqeni1n+0abFwKrvteahVnyHoFZXVCYErhmHnLIP3GsRfeAmC8ddtS+6LbBSKSHiX+rkv2cl3rJTTM/IFugZkXZl8Nc7enPmsE3F4Wqzb7fHRrcRXzY0oTRChQFt/OWpD1wu/fVAN0p1duPQa10iSyiY/8DfvfTDJ7Gror1rkQcu0SNM8Z33aLaiekTU0My/MszAQzYLp2r5dWFfiEC2r0eV0qsSukLeBMuhPQyJnN9ZSxN9OkY2S/i5TYIdsbZggj3AR/S28hTw6x+GFPImFtploBAaKnQtVgnVunvxALJJhbRTeZddxUFmA0sunIbmZn2rtNoYGzuBbCvSBfJnTQlDKyY9Y09jYZk3xSk4QryQAcN6TMIyzv8DWttrUsXjVUHtCPd9rlSqMrZYCkE=
  template:
    metadata:
      name: rsyncd-secret
      namespace: media
    type: Opaque
