apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyncd-backups
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rsyncd-backups
      app.kubernetes.io/name: rsyncd-backups
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rsyncd-backups
        app.kubernetes.io/name: rsyncd-backups
    spec:
      containers:
      - name: rsyncd-backups
        image: warrenrees/rsyncd-backups:0.1.9 # {"$imagepolicy": "flux-system:rsyncd-backups"}
        imagePullPolicy: IfNotPresent
        env:
        - name: RSYNC_PORT
          value: "8730"
        envFrom:
        - secretRef:
            name: rsyncd-secret
        readinessProbe:
          tcpSocket: { port: 8730 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket: { port: 8730 }
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 8730
          name: rsync
          protocol: TCP
        securityContext:
          runAsUser: 1000          # choose a non-root UID that exists in the image
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /backups
          name: backups
        - mountPath: /var/lib/rsyncd
          name: rsyncd-state
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: pvc-rsyncd-backups
      - name: rsyncd-state
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: plex
    metallb.universe.tf/ip-allocated-from-pool: myipaddresspool
  name: rsyncd-backups
  namespace: default
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.249
  ports:
  - name: rsync
    port: 873
    protocol: TCP
    targetPort: 8730
  selector:
    app.kubernetes.io/name: rsyncd-backups
    app.kubernetes.io/instance: rsyncd-backups
  type: LoadBalancer
