---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate-media
  namespace: default
spec:
  capacity:
    storage: 47Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfs/shared/frigate
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frigate-media
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-frigate-media
  resources:
    requests:
      storage: 47Ti
