apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: default
  labels:
    app: immich-machine-learning
    app.kubernetes.io/name: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
        app.kubernetes.io/name: immich-machine-learning
        app.kubernetes.io/instance: immich-machine-learning
        app.kubernetes.io/managed-by: flux
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.5.6-cuda # {"$imagepolicy": "flux-system:immich-machine-learning"}
          # volumeMounts:
          #   - mountPath: /cache
          #     name: model-cache
          # envFrom:
          #  - configMapRef:
          #     name: immich-env
          #     key: IMMICH_VERSION
          #readinessProbe:
          #  httpGet:
          #    path: /health
          #    port: 3003
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
              nvidia.com/gpu: 1
          #resources:
          #    requests:
          #        gpu.intel.com/i915: "1"
          #    limits:
          #        gpu.intel.com/i915: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: default
  labels:
    app.kubernetes.io/name: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app: immich-machine-learning
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
