---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-data
  namespace: default
spec:
  capacity:
    storage: 46Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  #mountOptions:
  #  - hard
  #  - nfsvers=4
  nfs:
    path: /var/nfs/shared/immich
    server: 10.255.255.79

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-data
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: nfs-immich-data
  resources:
    requests:
      storage: 46Ti

