---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: intel-gpu-device-plugin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: intel
  interval: 1m0s
  targetNamespace: intel-gpu-plugin
  values:
    nodeSelector:
      feature.node.kubernetes.io/pci-0300_8086.present: "true"
