---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: intel-gpu-plugin
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s
  releaseName: intel-gpu-plugin
  targetNamespace: intel-gpu-plugin
  values:
    image:
      tag: 0.26.1
    nodeSelector:
      feature.node.kubernetes.io/pci-0300_8086.present: "true"
