---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  interval: 1m0s
  targetNamespace: identity

  values:
    config:
      existingSecret: oauth2-proxy-secret

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

      path: /oauth2
      hosts:
        - auth.rees.ca
      tls:
      - secretName: oauth2-proxy-tls
        hosts:
          - auth.rees.ca

    extraArgs:
      provider: oidc
      oidc-issuer-url: https://sso.rees.ca/realms/master
      cookie-domain: .rees.ca
      whitelist-domain: .rees.ca
      skip-provider-button: 
      pass-authorization-header:
      email-domain: "*"
      cookie-secure: "false"
