---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secret
  namespace: default
spec:
  encryptedData:
    ADMIN_TOKEN: AgAf2Ot3Xz0RYduIRRG4J3iC7Dq9S0pwp7/RxVN3iFcSi7e9Rgv2SqN7Wel32VOMn8IGHxhN3ixffBehYu9cdbTu4LXuARSP4ZhFv9u6eRAdYmcGyHR0avJyVtjkxjWJFq/nMpRddDbgHsT8eJmt7ilHgsvCybrk83i87/ysiS/2AVic06TxsJE0W32v0oLGRsIrFu5bt4iO48cXKGflfBRdw61gPAHSt7NCm8SvsBzz/HB23qNdwi5EGP0TKNIlQx7O6inFlZjv6+ctke+G6dLf3xryw3M77wJGDYQQfXeQI9QReQTywuktx9v7BEkkb5Gzh51bqrA8xmsMxshCv82lVUGTPCa1Vsg3vy4L6P6gmWIpUh9trvBIqyY2j8yd6V2D6D4yEvLmmWiQGT0jGjr5jCkcHCVE5KWFinMaFHOIz9R7i3d4AHrNJ54ES78eUe/bsMWWZIune/pmzGzPEPpefbm+6GtAWR/8epfNxAiL3oKk4xrEqNuZxv6W89iklUXRXhTA6jwnZNyxdp1vj4KBWUCPuC7BFnx+uT4Ov2NPf8bJqfVIoSAXjY1OIZW7bXdAzZU6xOGk/fwUWnBv6I93xinXMHixaA9fhclAU5f6GtJPRRY3aYI2Ds+Il8S2crbsJ+Fa2qUjhuMx5tpriruuA89ZXIKefrxfwZu+xeUXvAtp+LLCWd5c6mg229ZPptlKJTw4jaMfoBtTOCn9dRA77+CSgvicWgGKHlO2aj5EVeDwbmGxuysdVXO7pJFCAQdQ2lhYP/Xwzvr3S+mCu0HOlZJrTxeBqMIryHhGd7kpW5P+v1EILxDekHhvYjnMEIu3nTvAHPTAbE1qJhCpbYEjGVA5d34I
    HIBP_API_KEY: AgBrnzOr4f0VOahL/taJcRe++ncSGxLb79E2wPjy6/swIBCiOf6SmLtO2J0tNfavC+6csgHJmREpmYi5TE1I1K7Rg/DktQ5iUB114SFutCtO/wNGfB9AyXvEd2zUm8Y1CmPM3fEh7ZiXTADEcqrG39KaoGVsw7jTfUQyhXk0nM7iNKjuLK/XDTJ/PA3yGC8FNMX2L5f6p83Fz/ZiSUTLkLYhm4uApMsLnrqf9QuTiiO2WRX7azz0t7JAZJWqElSL3xL5zgQ0xerDMYWmASlvfGTbLNykq98adw41zQ+knyfqfmkBzSru8q0reAa/D8dwVaqQOVSa+ALZKbYx8keHSKh9nSsAn2UBPUfi0ibpNg02Iq5yTllcIWtd2OWJtRSbInk8i5NcgchRDwRqV6iDDvo+wckWAy6/O6SzTBHCnGhpkj/pTo6HtVRBNqRg2vnjWeLuAGwWC3yMZEadZoFkArd9nGy/I2wT3FXFxccOgku41KlrSGFxDEuoyIoPqF9Kohi6X+SMMkQxzy4NU9ZBPqZBXiDNL7gf2AQT329W7Wpx7Qr7Rb8K9Cog1ub7YTaPVQxHy0RFa1kXnQadBTufWGloSzKsj8JoeeAVcQw65D8aII8U29Sk8xk/Nw+v1oSLkYSx8scqCAYouXY2Cw26+3fUgwq8VIIEXV23NPhY2BDR7fo/H9B+Mw8zQk+HNPHxASfLve+2WtbsWvR4Cy6wAK7miFj7+12Ae9/jem0CREPShg==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-secret
      namespace: default
