apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: default
spec:
  selector:
    matchLabels:
      app: vaultwarden
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - env:
        - name: TZ
          value: America\Toronto
        envFrom:
        - secretRef:
            name: vaultwarden-secret
        imagePullPolicy: IfNotPresent
        name: vaultwarden
        image: vaultwarden/server:1.34.3 # {"$imagepolicy": "flux-system:vaultwarden"}
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: vaultwarden-data
      hostname: vaultwarden
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: pvc-vaultwarden-data
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: default
spec:
  ports:
  - name: vaultwarden-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vaultwarden
  type: ClusterIP
