apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secret
  namespace: default
spec:
  encryptedData:
    ADMIN_TOKEN: AgCf3zcK1sY5L6mbOLMrUk32xLFYJgQu22cAS6CXXyCAXKie+6nYJSOYUqLMELaNt39qRbYff4isMTSVl3Q5TXmzcjn01NW7FCun089/PeHI27iH8VrKBV5HjYxCM31iznsMSBv+fLN5YBWghgPl533odZgiG1bNsEfUF/DzZPY7bonXh/ZXDi3c4xJILbG0bwq+TVbNMtz61Tf7Zyr6RKjYPtK8TXAq4YxsArhQ70VarBwO2aHH4H4VgWXKnpK/T7h/HsoESI0KRirfNBkvPAQnBj9XpSbdQtLpZZ0UEgyj2P0VCoF21r4QxaLgOt3wqfXZedAYNPsuO6tOE+K7Be8tVvihAre/YejhGZn2fIX0w68aVUgqjbaIlWWZcR9xMoZSm8idjtCuJeC9+WzT/J40dL7kVKgSIkiZx2/B1X7r8qJTb4L9nroKfvILy4EEJRWrrYAWsmaAf3sVgwNalvzOsoluBijpTScKlmnu7TAEoJKih//gKOOxNQCDw4PpLXEa4MeiUx28w2ANmXMVyAqiiDaAvtMTVFiTd75WSmOf/5MIjpt48Tf3NiKcvUeEV9PALtB3ElhvcSgYtrFYo7DY64Y3/Z34GapRMC9eajP1ZWlukS3wJKO1URBICsfXpxBlJFlItk3EoIrsS4jYl0QLghxilCia/45HEvv6uhONnjPXPfofr4A39LjmIV8wW+CDj0OAlUrCVreKxIP7aLbPpLfSDIflkENdGStPMkpZcAcoA85+W+jn/ln7Qu0gYykmIGHX6YxirWeg8AMLNmCp73oy6lZHz5SjJclbGmlvEQPyrWOSVifHtkVS17CgcI220DaCLt5eQZL3FQlyJhT2yuZYGfJe
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-secret
      namespace: default

