---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: identity
spec:
  encryptedData:
    ADMIN_TOKEN: AgAp3WutB5Ydc+xdypxcYBo055r3CKRwh9l9bDGxiciuc6TawCAWu9JVPady8U5INk/6QPFNjP9GEkJDoumn7IOkl4AXP71EniqCr/YTLpt++b3Qs2IWqF8WHrbTjQggAWwwichHFaOOGbdVajLrqjNKo3S3Pw0aAdLQ9tVLiw0hOR8GVcBpyjobwjPWBA+IssuZKCsHAGesymmj2EsE8WI/qJo+OtbiTmdpcZ5nz2TjwgrWq+xBtWCHyU8ULBDa7+wmb9f8N4H52od+WUAsZMLfeVEZOxRAHh/yC1TlpfoD0PTimWxj42YWyTLK0smFaZCyyxDn4qQFSqPkziRmPtH1ORkxUa+fTm3A0y4+lePp/nbip8dnuJA0yxZGy6xbgfndpGA/S4OLjqunRa/WfeejpMS6Ya7C9HvxyCmnxaZZp2j/7yj83DwUEgARtUlScadphP7sOV1aRcvL9N1G3pkzY7CWrLtf5mv20XN10fVbf3ed/2PQFCOvWTVq8l7AJsrN2ZHRgzktsByE+aE5jOZg1p1JdVUT/fRKf4yF50YgP2RhmB75UpuhnFAAbr1MMPGcfM0tTzdFTyDhDoBrmwUwLXxeBAyETlFSDTl+ITHltYK2gCp9tap1qcoFkIeoIcteoU4DjHXtLM6LVdchI7175EFY0J6UE9NGLYM3SAFDtRymqb/XaxHOSubWnSbHhn2XIP5TrTdLs6a/mKnRlaxsp8dPS1rVGsWxC0dTWoxFJMGqNENgStKjGxm22z3bSroGesZFfU+7sKHOZTRD67/2FKa20svcZ1sK9hUpj+gfX2Kdn5rZGcf85g1so0Cx7oIC8BfDriwcgt+hvB0+McJAOdMVdasv
    HIBP_API_KEY: AgA5YAIMclzBv4ky38JHfKm/jNd4hpfkwAzMrDWx9mdI5pu6zGtTsbkuPVpu7Wz7NpAOE2J8G88dF7G8OuyyHF8+CDe78GYsRmnTOqMJZ74GbVspLLrNSGFklf5GF/TLlQFWR+BNDE1tq1LHwa0SxUv1O8HP03dtpUjf41Fja3+59Y3k1ZJYeeBUvvpUL+uoNMiMne6Yq+eHr/p8dy7X6yT2O4i4NZqvN6MBkD7bxkKhlIVR99s6l5kuW8nxsd+DjvX/1YVoQDjHpVsYJza68HS+SMjdMy3Z83RU1QHlb+RIC7Sj5mSX4sFWD4GVJXRVih2R1Wtr7KQ/7rF3Bvy2zWGrT2IpGPm9Zx+lOQ9Zdsh59x0yskzQwZyselMO3rk+UycIwENySdLvF/JaPlN6gcinwQvONzPzaYp3tWrZTtInK7pafsDKOvcwCZh7jfkZhSIrn2sWfMmF2SphXQkcwsyEwvRAQ6X1IPlriXuOz4IbFBlpgCdbQd7sGzQ/T9C0Lxr0QSDa5vhOMX+CNPfpKPpBhuU9UHoavEIKDdF13/zMEhg03d863qVf+DcHC9t0bwoClFbrvHvpYGN0CrG1Kq09abbZoBDgUkbDymKvtkGAtKWbmVZRDvoB0f6dl6GhTg8nnbzjm1UAPUZactZgCLww6/tsQN2u3aZdyo+H2B8eDcZoYyxWwO7tZ7I4O0JFIH5P+X2vr58Die+DoV2rHjs4AzXfZIyKRGxgBBICT/kzRg==
  template:
    metadata:
      name: vaultwarden-secret
      namespace: identity
    type: Opaque
