apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1h0m0s
  releaseName: minecraft-server
  targetNamespace: default
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2026.2.1 # {"$imagepolicy": "flux-system:minecraft:tag"}
    minecraftServer:
      eula: true
      version: "LATEST"
      difficult: normal
      serviceType: LoadBalancer
      memory: 2048M
      loadBalancerIP: 10.0.0.34
      externalTrafficPolicy: Local
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
    rcon:
    persistence:
      dataDir:
        enabled: true
        existingClaim: pvc-minecraft
