apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zwavejs2mqtt
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s
  releaseName: zwavejs2mqtt
  targetNamespace: default
  values:
    image:
      tag: 9.0.2 # {"$imagepolicy": "flux-system:zwavejs2mqtt:tag"}
      pullPolicy: Always
    securityContext:
      privileged: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
        - host: zwavejs2mqtt.rees.ca
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zwavejs2mqtt
                port:
                  number: 8091
    persistence:
      config:
        enabled: true
        existingClaim: pvc-zwavejs2mqtt
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # USB attached Z-Wave controller
            - key: feature.node.kubernetes.io/usb-02_0658_0200.present
              operator: In
              values:
              - "true"
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/ttyACM0
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/ttyACM0
