apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 60m0s
  releaseName: pihole
  targetNamespace: default
  values:
    image:
      tag: 2026.02.0 # {"$imagepolicy": "flux-system:pihole:tag"}
    replicaCount: 1
    extraEnvVars: {"FTLCONF_LOCAL_IPV4": "10.0.0.35"}
    persistentVolumeClaim:
      enabled: true
      existingClaim: "pvc-pihole-config"
      accessModes:
      - ReadWriteOnce
    serviceWeb:
      loadBalancerIP: 10.0.0.35
      annotations:
        metallb.universe.tf/allow-shared-ip: mc-pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 10.0.0.35
      annotations:
        metallb.universe.tf/allow-shared-ip: mc-pihole-svc
      type: LoadBalancer
    serviceDhcp:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    admin:
      existingSecret: pihole
