---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: networking
spec:
  encryptedData:
    password: AgB+nNdJv2m6HKubNt5ALNOLdEQMXb85pAcTd0jF42Me8pKNsu5Fw1808oGlnCUoJEq8Z3eFisAgClPGFNRX8O6GVta+oBq1Aq2Jqy8ao+w2pkUVZiucdmPWliQZAwFRqfgDG3FDuDdsQBRfpTBmV5CBIplr9ahuix9sO71DjtpmZT0Kmej02IbGIM94Fwf5+sY19Y61XPzA28QFDNC4RXHGHptDD07hnv6zRnwm5uncsoTBhf4T3vTkzCNvdJzjFGSglL906MY+msFi7NU436TbLzLcZzaaJl6m7xQeyMebqyIwHbxPyOvvL3JCaoEZQ2g6v1F3ynsV/RYRL9G4YyJ+qjliDMjimB3cxCv9W89XaednEYggDuFXu2WT4ojCUh9KoS0LXbBEBtK//Byv++YoVQlZefrfYtBRqp6189LPKA6eqR5x8sZiDlifRLbi58oVFQKxcvxWpDKnxFHa5DvmBmhGbF88TPLC73e2xtYKbYy+qyQmN5w7AmHe3tRQ6MFIDDvPIo7COkUjeJxt9vWhpbLNms3aE7mpkIxxah2qZj2MzSqbIsm3U1VnDqHl2FYx+Th9jXI/2p6XYYBXubRqlOKMLrcAG8okHagQQCxpM3K2dFLGEVk8JG39iqoVVfeiWrwB2feNE7lX2+XUH2EBTsYe1EA2I+Fh5NzXBM0mmsPFjlx5HwQepgTlifzYsQ3N7Qs+rqMkTQ==
  template:
    metadata:
      name: pihole
      namespace: networking
    type: Opaque
